project_name: slack-status
release:
  github:
    owner: townewgokgok
    name: slack-status
#  draft: true
brew:
  github:
    owner: townewgokgok
    name: homebrew-tap
builds:
- goos:
#  - linux
  - darwin
  - windows
  goarch:
  - amd64
#  - "386"
#  goarm:
#  - "6"
  main: .
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: slack-status
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
    .Arm }}{{ end }}'
  files:
  - bash_complete
  - LICENSE*
  - README*
  - CHANGELOG*
#snapshot:
#  name_template: SNAPSHOT-{{ .Commit }}
