token: xoxp-...
templates:
  lunch:
    emoji: fork_and_knife
    text: Having lunch
  home:
    emoji: house
    text: Working remotely
playing_emoji: musical_note
playing_text: PLAYING
itunes:
  watch_interval_sec: 3
lastfm:
  watch_interval_sec: 15
  user_name: ...
  api_key: ...
  secret: ...
