# format placeholders
#   %A : Artist
#   %a : Album
#   %t : Title

slack:
  token: xoxp-...
itunes:
  watch_interval_sec: 3
  emoji: musical_note
  format: "PLAYING: %A - %a - %t"
lastfm:
  watch_interval_sec: 15
  emoji: musical_note
  format: "PLAYING: %A - %a - %t"
  user_name: ...
  api_key: ...
  secret: ...
templates:
  lunch:
    emoji: fork_and_knife
    text: Having lunch
  home:
    emoji: house
    text: Working remotely
